### ISSUE TITLE
Hard dependency on proper 1.2.0 makes it hard to use another version

### ISSUE THREAD

**Issue by NobbZ** [ferd/rebar3_proper#21]
`rebar3_proper` does not even use `proper` for itself and I can't access it without specifying it as a top level dependency.

Also proper 1.2.0 does create deprecation warnings on a current OTP. Therefore I want to use proper from master where the warnings are fixed.

Still proper 1.2.0 is pulled and compiled, even for prod, because we can't have plugins in profiles.

Last but not least running proper does fail randomly when not using 1.2.0.

**Comment by ferd** [comment]
`rebar3 proper` calls proper to run tests and that is why it depends on it. You should be able to pick the PropEr version you need from your profile deps in rebar3. If this is not taking place, then *that* is likely a bug.

I'm guessing it wouldn't fix the warnings, but since the plugin requires calls to `proper` it should depend on `proper`.

**Comment by NobbZ** [comment]
Hm, yes you are right, of course we depend on proper to start it. I haven't considered that.

So let me see if I can reproduce the randomly failing proper starts on another machine, or if I can somehow trace the origin on the machine where they failed.

Still, the emitted warnings during compilation troubled the QA of a customer, so that I currently strip the plugin line from the rebar file on the build server, to not pull in rebar3_proper at all and thus not emit any warnings anymore.

**Comment by fenollp** [comment]
@NobbZ Have you tried with this rebar3 setting? `{deps_error_on_conflict, false}.`

**Comment by ferd** [comment]
One option is to also just make the plugin appear in the `test` profile. You'll need to call `rebar3 as test proper` but that will prevent PropEr from being fetched as part of regular non-test builds.

**Comment by NobbZ** [comment]
> One option is to also just make the plugin appear in the test profile.

I thought I read in the rebar docs that this is not allowed. But I tried and it just works.

Now the last thing remaining are the randomly failing runs when versions differ. I try to get more information about that during the remainder of the week.

**Comment by fenollp** [comment]
This should probably be closed.

**Comment by ferd** [comment]
I'll close this. warnings would ideally be fixed by @manopapad, @kostis, or @thegeorge publishing a new hex package of PropEr?

**Comment by ferd** [comment]
I'll also merge a PR today that removes the runtime dependency entirely from the plugin; I've checked and the PropEr version used by tests is sufficient.

**Comment by kostis** [comment]
We will make a new (hex) version of PropEr once the targeted PBT API is considered stable, most likely within May.

**Comment by ferd** [comment]
Sounds good! Thanks for the update :) I'll eagerly await it then, and will try to add it to the print copy of PropEr Testing.
