### ISSUE TITLE
Deprecated calling warning

### ISSUE THREAD

**Issue by gilbertwong96** [ferd/rebar3_proper#36]
Hi, @ferd, when I execute `rebar3 proper` in my project, it warns me that
```bash
===> Calling deprecated rebar_erlc_compiler compiler module. This module has been replaced by rebar_compiler and rebar_compiler_erl, but will remain available.
```
What about replacing the calling `rebar_erlc_compiler` with another two modules in rebar3_proper code?

**Comment by ferd** [comment]
Yeah, we'll need to do that _but_ also keep the existing compiler based on availability so that the plugin keeps working on older rebar3 releases.

**Comment by gilbertwong96** [comment]
Great!
