### ISSUE TITLE
How to silent usless warnings when using PropEr?

### ISSUE THREAD

**Issue by Zabrane** [ferd/rebar3_proper#39]
Hi @ferd 

Is there a way to silent these warnings? I see no reason to add `TypeSpec` to properties IMHO.

```
$ rebar3 proper
test/prop_btree.erl:8: Warning: missing specification for function prop_btree_insert/0
test/prop_btree.erl:15: Warning: missing specification for function prop_btree_delete/0
[...]
```

My `rebar.config`:
```
{require_otp_vsn, "2+"}.

{deps, []}.

{project_plugins, [rebar3_proper]}.

{profiles,
   [{test, [
          {deps, [ {proper, {git, "https://github.com/proper-testing/proper.git",
                             {branch, "master"}}}
                 , {covertool, {git, "https://github.com/covertool/covertool.git",
                                {branch, "master"}}}
                 ]}
         ]}
 ]}.
```
Thanks

**Comment by ferd** [comment]
Those are compiler options that would generally not be turned on by default and not run only for the rebar3_proper plugin (at least the new versions don't compile their own code anymore.

Which version of the plugin are you using, can you try a new one, and do you have any other compiler config around (either global rebar.config file, or things passed via the ENV variable `ERL_COMPILER_OPTIONS` ?

**Comment by Zabrane** [comment]
@ferd here is my `rebar.config`

```
{erl_opts,
 [bin_opt_info,
  warn_unused_vars,
  warn_export_all,
  warn_shadow_vars,
  warn_unused_import,
  warn_unused_function,
  warn_bif_clash,
  warn_unused_record,
  warn_deprecated_function,
  warn_obsolete_guard,
  strict_validation,
  warn_export_vars,
  warn_exported_vars,
  warn_missing_spec,
  fail_on_warning,
  warn_untyped_record,
  debug_info]}.

{deps, []}.

{project_plugins, [rebar3_proper]}.

{profiles,
   [{test, [
          {deps, [ {proper, {git, "https://github.com/proper-testing/proper.git",
                             {branch, "master"}}}
                 , {covertool, {git, "https://github.com/covertool/covertool.git",
                                {branch, "master"}}}
                 ]}
         ]}
 ]}.
```

I'm running this version of the plugin
```
{application,rebar3_proper,
             [{description,"Run PropEr test suites"},
              {vsn,"0.12.1"},
              {registered,[]},
```

Is there a way to tell `rebar3` to not apply `erl_opts` on `test` modules?

**Comment by ferd** [comment]
you have the `warn_missing_spec` warning turned on, that's what causes the compiler to complain about the missing spec.

**Comment by Zabrane** [comment]
> you have the `warn_missing_spec` warning turned on, that's what causes the compiler to complain about the missing spec.

Yes, i'm aware of that.

Question: when you write `Eunit|PropEr` tests, do you write `typespec` for them?

**Comment by ferd** [comment]
Just saw the edit about the test modules. Currently there is no way to specify that. If the compiler supported a boolean approach you could set erl_opts in the test profile with a negative option (i.e. `{warn_missing_spec, false}`), but the compiler options don't support setting that so you're kind of stuck with a non-profileable option. A possible workaround is to have a stricter profile (i.e. `prod` or `strict`) that adds these warnings.

I do not ever turn that warning on (it's not even documented), so I never encountered that problem before.

**Comment by Zabrane** [comment]
>  A possible workaround is to have a stricter profile (i.e. `prod` or `analysis`) that adds these warnings.

Could you please show me or point to an `prod or analysis` rebar.config examples?
I'm new to rebar3. Many thanks.

> I do not ever turn that warning on, so I never encountered that problem before.

I see.

**Comment by ferd** [comment]
```erlang
{erl_opts,
 [bin_opt_info,
  warn_unused_vars,
  warn_export_all,
  warn_shadow_vars,
  warn_unused_import,
  warn_unused_function,
  warn_bif_clash,
  warn_unused_record,
  warn_deprecated_function,
  warn_obsolete_guard,
  strict_validation,
  warn_export_vars,
  warn_exported_vars,
  fail_on_warning,
  warn_untyped_record,
  debug_info]}.

{deps, []}.

{project_plugins, [rebar3_proper]}.

{profiles,
   [{test, [
        {deps, [ {proper, {git, "https://github.com/proper-testing/proper.git",
                             {branch, "master"}}}
                 , {covertool, {git, "https://github.com/covertool/covertool.git",
                                {branch, "master"}}}
                 ]}
         ]},
        {strict, [{erl_opts, [warn_missing_spec]}]}
 ]}.
``` 
Then if you call `rebar3 compile` or `rebar3 proper` the option is never triggered, but if you call `rebar3 as strict compile` or `rebar3 as strict proper` now it will complain by adding the `warn_missing_spec` option to the set of `erl_opts` for a given run.

Generally I would use a CI step where things are compiled-as-strict to give all the warnings in case the developer forgot to do it locally.

**Comment by Zabrane** [comment]
Amazing. Thanks a lot
