### ISSUE TITLE
Application's include directory is missing from include path when building property tests

### ISSUE THREAD

**Issue by tokenrove** [ferd/rebar3_proper#8]
When I run `rebar3 proper`, the compilation of the `test/prop_*.erl` files fails as they reference include files in my application's `include/` directory.  Since eunit successfully compiles files with the same include references, this seems like a bug.

Sorry I haven't had time to submit a patch with this.

Hopefully minimal reproduction:

```
% rebar3 new app rebar3_proper_include_issue && cd rebar3_proper_include_issue
% cat > rebar.config <<REBAR_CONFIG
{deps, [{proper, "1.1.1-beta"}]}.
{plugins, [rebar3_proper]}.
REBAR_CONFIG
% mkdir test && cat > test/prop_test.erl <<PROP_TEST
-module(prop_test).
-include_lib("proper/include/proper.hrl").
-compile([export_all]).
-include("foo.hrl").
PROP_TEST
% mkdir include && touch include/foo.hrl
```

Note that `rebar3 eunit` compiles this empty test, while `rebar3 proper` complains:

```
===> Verifying dependencies...
===> Compiling rebar3_proper_include_issue
===> Compiling test/prop_test.erl failed
test/prop_test.erl:4: can't find include file "foo.hrl"
```

**Comment by ferd** [comment]
Can you specify the versions of rebar3 used for this, and the version of the plugin used?

**Comment by tokenrove** [comment]
Of course.  Sorry about that.

```
% rebar3 --version
rebar 3.2.0 on Erlang/OTP 18 Erts 7.3.1
% rebar3 proper
===> Fetching rebar3_proper ({pkg,<<"rebar3_proper">>,<<"0.6.2">>})
===> Downloaded package, caching at /home/julian/.cache/rebar3/hex/default/packages/rebar3_proper-0.6.2.tar
===> Fetching proper ({pkg,<<"proper">>,<<"1.1.1-beta">>})
===> Downloaded package, caching at /home/julian/.cache/rebar3/hex/default/packages/proper-1.1.1-beta.tar
```

**Comment by ferd** [comment]
Have you considered using `-include_lib("libname/include/foo.hrl").` ?

**Comment by tokenrove** [comment]
I can do that, and thank you for the suggestion, but the difference in behavior from eunit is a little disconcerting.  Do you feel that eunit's behavior is too magical?

**Comment by ferd** [comment]
That's a good question. I didn't consider EUnit's behaviour. In this case I believe it's just that the test files are not seen as being part of the application being tested, just users of the applications. As such, the paths are not being added, and this lets things transparently work with test suites even if there's multiple umbrella apps in a project.

I could very well accept that if the project is a top-level app, src/ and include/ are added to the include path for the compiler.

**Comment by jadeallenx** [comment]
This just bit me, mostly because I expected `eunit` like behavio(u)r.

It would be real handy if the proper plugin would inject the top level directories automatically.

**Comment by ferd** [comment]
I think the Eunit provider does some magic; it does not depend on the `compile` task the way `rebar3 proper` does, and overall you would have the crash/failure in any case.

In my case I could trigger the failure by calling `rebar3 as test compile`, nothing to do with the plugin itself -- if you can verify that the same thing happens to you, that would help.

A workaround instead of using `-include_lib` is to add `{erl_opts, [{i, "src/"}]}` to the `test` profile. Will dig into it a bit more.

**Comment by talentdeficit** [comment]
`eunit` and `ct` both have some magic going on for the test profile

neither mess with the include dirs tho, so i'm unsure why this works with `rebar3 eunit` but not `rebar3 as test compile`. i'll look into it also

**Comment by ferd** [comment]
@talentdeficit think I found it. Check this diff:

``` diff
diff --git a/src/rebar_erlc_compiler.erl b/src/rebar_erlc_compiler.erl
index b148172..e7dccc2 100644
--- a/src/rebar_erlc_compiler.erl
+++ b/src/rebar_erlc_compiler.erl
@@ -224,7 +224,7 @@ compile_dirs(RebarOpts, BaseDir, SrcDirs, OutDir, Opts) ->
                                    true -> ErlOptsFirst;
                                    false -> ErlOpts
                                end,
-                    internal_erl_compile(C, BaseDir, S, OutDir, ErlOpts1)
+                    internal_erl_compile(C, BaseDir, S, OutDir, ErlOpts1, RebarOpts)
             end)
     after
         true = digraph:delete(SubGraph),
@@ -518,11 +518,13 @@ expand_file_names(Files, Dirs) ->
       end, Files).

 -spec internal_erl_compile(rebar_dict(), file:filename(), file:filename(),
-    file:filename(), list()) -> ok | {ok, any()} | {error, any(), any()}.
-internal_erl_compile(Opts, Dir, Module, OutDir, ErlOpts) ->
+    file:filename(), list(), rebar_dict()) -> ok | {ok, any()} | {error, any(), any()}.
+internal_erl_compile(Opts, Dir, Module, OutDir, ErlOpts, RebarOpts) ->
     Target = target_base(OutDir, Module) ++ ".beam",
     ok = filelib:ensure_dir(Target),
-    AllOpts = [{outdir, filename:dirname(Target)}] ++ ErlOpts ++
+    PrivIncludes = [{i, filename:join(Dir, Src)}
+                    || Src <- rebar_dir:src_dirs(RebarOpts, ["src"])],
+    AllOpts = [{outdir, filename:dirname(Target)}] ++ ErlOpts ++ PrivIncludes ++
         [{i, filename:join(Dir, "include")}, {i, Dir}, return],
     case compile:file(Module, AllOpts) of
         {ok, _Mod} ->
```

The issue is that the include paths we had at compile time have `$DIR/include` and `$DIR` in there, but not any of the matches for `$DIR/src` and other similar paths. As such, the private `.hrl` file in the source directories would not be carried around. The patch I tried fixes the bug in a toy case for me by mandating that `src_dirs` is used to add to the include paths.

**Comment by ferd** [comment]
Not that we could possibly remove the `{i, Dir}` entry there and little stuff should break, though it may be there for a reason.

**Comment by tokenrove** [comment]
`rebar3 as test compile` doesn't error out for the example I gave and version of rebar.  Maybe the test profile behavior changed since then?  (Note that I don't care either way; I gave up and rewrote all our tests to not use `-include`, but this behavior is still a little mysterious.  Note also that `rebar3 proper` fails even if the usage of `-include` is only in eunit tests that contain no properties, since it builds all of `test`.)

**Comment by ferd** [comment]
Hm, yeah. The problem highlighted by your case is because the include takes place in the `include/` directory instead of `src/` so it passes the compile step and then dies at proper's level. The same fix that is being brought to the erlc compiler would need to be carried into rebar3 proper. I have an idea of how to proceed on that one and may cover the case in the next few days.

**Comment by ferd** [comment]
https://github.com/ferd/rebar3_proper/pull/10 should contain the fix; right now it will only work with files in `include/` and not `src/` since the latter will require a rebar3 compiler patch to even run the proper plugin.
